theme = "terminal"

baseurl = "https://jstockley.com"
languageCode = "en-us"
title = "Jack Stockley's Personal Site"

[params]
    themeColor = "blue"
    centerTheme = true
    showMenuItems = 5
    

[languages]
  [languages.en]
    languageName = "English"
    title = "Jack Stockley's Personal Site"

    [languages.en.params.logo]
      logoText = "Jack Stockley"
      logoHomeLink = "/"

    [languages.en.menu]
    [[languages.en.menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = 1
    [[languages.en.menu.main]]
        identifier = "courses"
        name = "Courses"
        url = "/courses"
        weight = 2    
    [[languages.en.menu.main]]
        identifier = "education"
        name = "Education"
        url = "/education"
        weight = 3
    [[languages.en.menu.main]]
        identifier = "experience"
        name = "Experience"
        url = "/experience"
        weight = 4
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects"
        weight = 5
